### PR TITLE
Update rand, rand-core (and merlin)

### PR DESCRIPTION
**Pull request by bltavares**
Updates rand and rand-core to their latest versions. It also requires updating merlin to their latest version to match the rand dependencies.

This PR contains commits from https://github.com/dalek-cryptography/ed25519-dalek/pull/156

Closes https://github.com/dalek-cryptography/ed25519-dalek/pull/156

### CODE REVIEW

**Review by shekohex — APPROVED** [review]

**Comment by robjtede** [comment]
A needed change but would be technically breaking unless a version range like `>=0.7, <0.9` is used.

**Comment by toxeus** [comment]
This crate could easily prevent such breaking changes by re-exporting crates that are used by its public API such as `rand`.
I made a PR to fix this https://github.com/dalek-cryptography/ed25519-dalek/pull/159.

Well-maintained crates are doing this, e.g. [secp256k1](https://docs.rs/secp256k1/0.20.1/secp256k1/index.html#reexports).

**Comment by roblabla** [comment]
> This crate could easily prevent such breaking changes by re-exporting crates that are used by its public API such as rand

It'd still be a breaking change though, as users could still use `rand` without going through the public re-export. It'd still be a good idea for usability reasons though.

**Comment by toxeus** [comment]
Agreed, the user can always shoot herself in the foot. There's no silver bullet but it would be at least an improvement.

**Comment by roblabla** [comment]
Bump. I'm currently keeping rand 0.7 around for dalek-cryptography, and it's causing me a bit of trouble, as the rest of the ecosystem is moving towards rand 0.8. Is there any way I can help moving this forward? `merlin` seems to have been updated (docs.rs lists latest version, 3.0.0, as using the correct version of rand). What are the remaining steps?

**Comment by toxeus** [comment]
This project's maintenance seems to have dropped significantly. No activity by the maintainers on pull-requests and no commits since September 2020. I'm considering to maintain a fork and make sure that dependency updates land in a timely manner which is not really difficult using the auto-update tooling widely available (renovate-bot, dependa-bot, etc.). Let me know if there's interest. That might help my motivation :)

**Comment by thomaseizinger** [comment]
> I'm considering to maintain a fork

This has already happened for the primary dependency of this crate: `curve25519-dalek`: https://github.com/zkcrypto/curve25519-dalek-ng

There is an open issue about forking `ed25519-dalek` into the same organization: https://github.com/zkcrypto/curve25519-dalek-ng/issues/8

**Comment by toxeus** [comment]
I've migrated to https://github.com/jedisct1/rust-ed25519-compact. It's well maintained and works great.

**Comment by rozbb** [comment]
All deps have been updated in the `release/2.0` branch. We will be cutting a prerelease soon.

**Pull request closed without merging**
