### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by exrook**
Update rand to verion 0.4
Update sha2 and digest to version 0.7
Update hex to version 0.3

### CODE REVIEW

**Comment by newpavlov** [comment]
I plan to update `sha2` and `digest` to `v0.8` hopefully next month. It could be worth to wait until then.

**Comment by isislovecruft** [comment]
Hi @exrook, thanks for the PR! I'm happy to merge now and also bump it again in a month when @newpavlov updates those crates.

**Comment by tarcieri** [comment]
@newpavlov what's the story on digest 0.8?

**Comment by tarcieri** [comment]
:shipit:

**Pull request merged**
