### PR TITLE
Implement plain custom digest functions

### PR DESCRIPTION
**Pull request by dpc**
Any chance this could be supported, at least temporarily, for backward-compatibility with how things previously worked?

### CODE REVIEW

**Comment by tarcieri** [comment]
This seems trivial to implement yourself atop `curve25519-dalek`

**Comment by dpc** [comment]
I'd be happy to put the `Digest` stuff under a `feature` flag.

**Comment by dpc** [comment]
Alternatively I'd be happy to help maintain some fork of `ed25519-dalek-ext` or something.I don't really feel comfortable doing even "trivial" stuff on my own.

**Comment by burdges** [comment]
I'd think an ed25519-oops crate could be a fork of the older ed25519-dalek, so you could use both concurrently.  If you're only worried about expanded secret key generation from the secret key then you could maybe transition to storing the full expanded secret key.  If you need alternative hashing in signing then you could transition with a version number or trial verification probably.

**Comment by dpc** [comment]
So custom digest feature is just going to get removed from `ed25519-dalek`? :/

**Comment by dpc** [comment]
I think I might just take the hit, implement a way for my users to convert their old signed artifacts, and just change everything to be SHA-512-based. However - can anyone asure me that I won't need to do it ever again? I mean ... I was using pre.0 and `Digest` support got slashed. Now I'll use pre.1, and there might be pre.2, pre.3 :D

**Comment by burdges** [comment]
I think hashing was changed to comply with the standard.

**Comment by tarcieri** [comment]
"Ed25519", both in RFC8032 form and before, has always used SHA-512

**Comment by dpc** [comment]
@tarcieri `ed25519` had functions to allow any hashing to be used under the hood, with `SHA-512` being a default, I believe. I wasn't aware of RFC8032, or the fact that ed25519 intention was to implement it. I still don't understand all the nuances here. I'd really appreciate if you could help me get answers to  https://github.com/dalek-cryptography/ed25519-dalek/issues/69#issuecomment-482783711 . @tarcieri

**Comment by dpc** [comment]
I've got my answers, and looks like I don't need this stuff now.

**Pull request closed without merging**
